# Generated by Django 5.0.7 on 2024-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fdbk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flvr_sugg', models.CharField(max_length=255)),
                ('alrgy_warn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flvr_name', models.CharField(max_length=100)),
                ('szn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
